name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Use the latest stable Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build # Modify this step if your project doesn't need building

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Upload Environment Variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" > .env
          echo "JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}" >> .env
          echo "PORT=${PORT}" >> .env

      - name: Restart Application with PM2
        run: |
          pm2 describe my-app > /dev/null
          if [ $? -eq 0 ]; then
            pm2 restart my-app
          else
            pm2 start ./dist/index.js --name "my-app" --interpreter node --interpreter-args "--enable-source-maps"
          fi
          pm2 save
